export const refs = {
  body: document.body,
  burger: document.querySelector('.burger-container'),
  burgerBtn: document.querySelector('.burger-icon'),
  burgerBtnClose: document.querySelector('.btn-close'),
  burgerMenuLink: document.querySelector('.menu-link'),
  burgerMenuBtn: document.querySelector('.button-menu'),
  feedbackList: document.querySelector('.js-feedback-list'),
  burger: document.querySelector('.burger-container'),
  burgerBtn: document.querySelector('.burger-icon'),
  burgerBtnClose: document.querySelector('.btn-close'),
  burgerMenuLink: document.querySelector('.menu-link'),
  burgerMenuBtn: document.querySelector('.button-menu'),
  wrapper: document.querySelector('.about-us-list'),
  items: document.querySelectorAll('.about-us-item'),
  desertsList: document.querySelector('.desert-cards'),
  desertsCategories: document.querySelector('.desert-categories'),
  desertsCategoriesSelect: document.querySelector('.desert-categories-select'),
  desertsEmpty: document.querySelector('.desert-empty'),
  desertsLoadMore: document.querySelector('.desert-load-more'),
};
